model = "PrimeIntellect/Qwen3-0.6B-Reverse-Text-SFT"
max_steps = 200
batch_size = 512
rollouts_per_example = 8

[sampling]
max_tokens = 900

[[env]]
id = "herr-professor/f1-strategy"
args = { use_tools = true, multi_turn = true, multi_env = true, max_tracks = 4, eval_season = 2024 }
