model = "meta-llama/Llama-3.2-3B-Instruct"
max_steps = 200
batch_size = 256
rollouts_per_example = 8

[sampling]
max_tokens = 700

[[env]]
id = "herr-professor/f1-strategy"
args = { use_tools = true, multi_turn = true, multi_env = true, max_tracks = 4, eval_season = 2024 }
